### ISSUE TITLE
lowrisc tutorials invisible in latest version of lowrisc-site

### ISSUE THREAD

**Issue by jrrk** [lowRISC/lowrisc-site#35]
The fresh look to the lowrisc site is welcome, especially the new pictures, however the tutorials for code releases seem to be invisible or not very obvious. Since we plan to make another 64-bit release shortly, a penny for your thoughts.

**Comment by asb** [comment]
Good point, Jonathan. I think we want to add it back to the top-level navbar given that these tutorials are obviously very popular and well appreciated. But probably tweak the docs index page so it makes clear that these are focused around the 64-bit platform strand of work, rather than an exhaustive listing of all our work.
